### ISSUE TITLE
missing reference (ApplySpecification)

### ISSUE THREAD

**Issue by safakseyrek** [wanghu24/generic-repository-pattern-core#1]
Hey,

IncludeString, sort, filter are missing methods and `spec.Includes` property is not assignable to `qry.Include()`.

Error row:
` return qry.Include(spec.Includes).IncludeString(spec.StringIncludes).Sort(spec.Order).Filter(spec.Filters);
`

Can you share missing methods?

**Comment by wanghu24** [comment]
added queryable extensions
